language: node_js
node_js:
  - "8.9.3"
before_install:
  - npm i -g npm@5.6.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: heroku
  app: skycop-task
  api_key:
    secure: $HEROKU_API_KEY